### ISSUE TITLE
Dbus authentication failed

### ISSUE THREAD

**Issue by castorinop** [muesli/pam-beacon#2]
im trying that work on fedora 28. i add debug flag.
$ sudo dmesg 
DEBU[0002] argv: [debug]                                
DEBU[0002] Parsing MAC addresses from /home/user/.authorized_beacons 
DEBU[0002] Looking for beacon XX:XX:XX:XX:XX:XX...      
DEBU[0002] Exec: [btmgmt --index hci0 power on]         
ERRO[0002] dbus: authentication failed                  
DEBU[0003] Discovered devices:                          
ERRO[0003] dbus: authentication failed 

It only happens when I call sudo from a terminal once the session has begun through the graphical interface.

**Comment by castorinop** [comment]
testing working
$ go run main.go XX:XX:XX:XX:XX:XX
DEBU[0000] Looking for beacon XX:XX:XX:XX:XX:XX...      
DEBU[0000] Exec: [btmgmt --index hci0 power on]         
DEBU[0000] Cached devices:                              
DEBU[0000] name=BT Device addr=XX:XX:XX:XX:XX:XX rssi=0 trusted=true tx=0 connected=true 
INFO[0000] Beacon XX:XX:XX:XX:XX:XX found!

**Comment by muesli** [comment]
@castorinop Interesting, this sounds like a dbus auth issue (which in turn might be systemd / policy related). Which service do you try to use pam-beacon with, here?

**Comment by castorinop** [comment]
@muesli almost terminal, sudo commands

**Comment by castorinop** [comment]
Another test:
- logged in Graphical interface, connect BT
- switch tty3
- login: USER (enter)
DEBU[0000] argv: [debug]
DEBU[0000] Looking for beacon XX:XX:XX:XX:XX:XX...
DEBU[0000] Exec: [btmgmt --index hci0 power on]
DEBU[0000] Cached devices:
DEBU[0000] name=BT Device addr=XX:XX:XX:XX:XX:XX rssi=0 trusted=true tx=0 connected=true
INFO[0000] Beacon XX:XX:XX:XX:XX:XX found!
$ sudo ls 
DEBU[0002] argv: [debug]
DEBU[0002] Parsing MAC addresses from /home/user/.authorized_beacons
DEBU[0002] Looking for beacon XX:XX:XX:XX:XX:XX...
DEBU[0002] Exec: [btmgmt --index hci0 power on]
ERRO[0002] dbus: authentication failed
DEBU[0003] Discovered devices:
ERRO[0003] dbus: authentication failed

**Comment by ju916** [comment]
I can confirm those errors on Ubuntu 18.04 LTS.
What I did: for testing included pam_beacon in sudo. 
The result is:
```
ERRO[0000] dbus: authentication failed                  
ERRO[0001] dbus: authentication failed                  
^CDas hat nicht funktioniert, bitte nochmal probieren.
ERRO[0010] dbus: authentication failed                  
ERRO[0011] dbus: authentication failed                  
Das hat nicht funktioniert, bitte nochmal probieren.
ERRO[0020] dbus: authentication failed                  
ERRO[0021] dbus: authentication failed                  
sudo: 3 Fehlversuche bei der Passwort-Eingabe
```
Finally killed sudo. I am willing to do more testing, if I get directions, what to do.

**Comment by ju916** [comment]
When I use pam_beacon with xscreensaver I get similar errors (and finally a crash):
```
xscreensaver: 13:11:32: pam_start ("xscreensaver", "ju", ...) ==> 0 (Success)
xscreensaver: 13:11:32:   pam_set_item (p, PAM_TTY, ":0.0") ==> 0 (Success)
xscreensaver: 13:11:32:   pam_authenticate (...) ...
ERRO[0010] /org/bluez/hci0/dev_5D_5F_5C_49_9E_FD: Failed to get properties: dbus: connection closed by user 
ERRO[0011] /org/bluez/hci0/dev_00_16_94_1C_35_86: Failed to get properties: dbus: connection closed by user 
ERRO[0012] /org/bluez/hci0/dev_F0_99_B6_17_0F_A0: Failed to get properties: dbus: connection closed by user 
ERRO[0013] /org/bluez/hci0/dev_20_74_CF_0D_59_F8: Failed to get properties: dbus: connection closed by user 
ERRO[0014] dbus: connection closed by user              
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f3a9b4dbee4]
goroutine 17 [running, locked to thread]:
github.com/muka/go-bluetooth/bluez/profile.(*ObjectManager).Unregister(0x0, 0xc4200da240, 0x0, 0xc42005dc78)
	/home/ju/go/src/github.com/muka/go-bluetooth/bluez/profile/ObjectManager.go:49 +0x24
github.com/muka/go-bluetooth/api.(*Manager).Close(0xc42000c1a0)
	/home/ju/go/src/github.com/muka/go-bluetooth/api/Manager.go:249 +0x39
github.com/muka/go-bluetooth/api.Exit()
	/home/ju/go/src/github.com/muka/go-bluetooth/api/api.go:17 +0x3d
main.closeBluetooth()
	/home/ju/go/src/pam-beacon/main.go:50 +0x29
main.findDevice(0xc42019a820, 0x11, 0xc420238900)
	/home/ju/go/src/pam-beacon/main.go:68 +0x34b
main.goAuthenticate(0x55a354f4bc80, 0xc400000000, 0x55a354f4dc40, 0x0, 0x0, 0x30)
	/home/ju/go/src/pam-beacon/main.go:181 +0x199
main._cgoexpwrap_b920933af15c_goAuthenticate(0x55a354f4bc80, 0x55a300000000, 0x55a354f4dc40, 0x0, 0x0, 0x55a354f4bc80)
	_cgo_gotypes.go:55 +0x53
Abgebrochen (Speicherabzug geschrieben)
```
I can provide a crash report if needed.
